CREATE TABLE User1 (
    UserID INT PRIMARY KEY NOT NULL,
    UserName CHAR UNIQUE NOT NULL,
    Name CHAR NOT NULL,
    PASSWORD CHAR NOT NULL
);


CREATE TABLE Room (
    RoomID INT PRIMARY KEY NOT NULL,
    Name CHAR NOT NULL
);


CREATE TABLE TimeSlot (
    TimeSlotID INT PRIMARY KEY NOT NULL,
    StartTime DATE NOT NULL,
    EndTime DATE NOT NULL,
    IsAvailable BOOLEAN NOT NULL
);


CREATE TABLE Reservation (
    ReservationID INT PRIMARY KEY NOT NULL,
    ReservationDate DATE NOT NULL,
    FK_TimeSlotID INT NOT NULL,
    FK_RoomID INT NOT NULL,
    FK_UserID INT NOT NULL,
    FOREIGN KEY (FK_TimeSlotID) REFERENCES TimeSlot(TimeSlotID) ON DELETE CASCADE,
    FOREIGN KEY (FK_RoomID) REFERENCES Room(RoomID) ON DELETE CASCADE,
    FOREIGN KEY (FK_UserID) REFERENCES User1(UserID) ON DELETE CASCADE
);
