# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import reservation_pb2 as reservation__pb2


class ReservationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PingServer = channel.unary_unary(
                '/reservation.ReservationService/PingServer',
                request_serializer=reservation__pb2.PingServerRequest.SerializeToString,
                response_deserializer=reservation__pb2.PingServerResponse.FromString,
                )
        self.CreateAccount = channel.unary_unary(
                '/reservation.ReservationService/CreateAccount',
                request_serializer=reservation__pb2.CreateAccountRequest.SerializeToString,
                response_deserializer=reservation__pb2.CreateAccountResponse.FromString,
                )
        self.Login = channel.unary_unary(
                '/reservation.ReservationService/Login',
                request_serializer=reservation__pb2.LoginRequest.SerializeToString,
                response_deserializer=reservation__pb2.LoginResponse.FromString,
                )
        self.Logout = channel.unary_unary(
                '/reservation.ReservationService/Logout',
                request_serializer=reservation__pb2.LogoutRequest.SerializeToString,
                response_deserializer=reservation__pb2.LogoutResponse.FromString,
                )
        self.FetchAvailableSlots = channel.unary_unary(
                '/reservation.ReservationService/FetchAvailableSlots',
                request_serializer=reservation__pb2.FetchAvailableSlotsRequest.SerializeToString,
                response_deserializer=reservation__pb2.FetchAvailableSlotsResponse.FromString,
                )
        self.MakeReservation = channel.unary_unary(
                '/reservation.ReservationService/MakeReservation',
                request_serializer=reservation__pb2.MakeReservationRequest.SerializeToString,
                response_deserializer=reservation__pb2.MakeReservationResponse.FromString,
                )
        self.ViewReservations = channel.unary_unary(
                '/reservation.ReservationService/ViewReservations',
                request_serializer=reservation__pb2.ViewReservationsRequest.SerializeToString,
                response_deserializer=reservation__pb2.ViewReservationsResponse.FromString,
                )
        self.CancelReservation = channel.unary_unary(
                '/reservation.ReservationService/CancelReservation',
                request_serializer=reservation__pb2.CancelReservationRequest.SerializeToString,
                response_deserializer=reservation__pb2.CancelReservationResponse.FromString,
                )


class ReservationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PingServer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Logout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FetchAvailableSlots(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MakeReservation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ViewReservations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelReservation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReservationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PingServer': grpc.unary_unary_rpc_method_handler(
                    servicer.PingServer,
                    request_deserializer=reservation__pb2.PingServerRequest.FromString,
                    response_serializer=reservation__pb2.PingServerResponse.SerializeToString,
            ),
            'CreateAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAccount,
                    request_deserializer=reservation__pb2.CreateAccountRequest.FromString,
                    response_serializer=reservation__pb2.CreateAccountResponse.SerializeToString,
            ),
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=reservation__pb2.LoginRequest.FromString,
                    response_serializer=reservation__pb2.LoginResponse.SerializeToString,
            ),
            'Logout': grpc.unary_unary_rpc_method_handler(
                    servicer.Logout,
                    request_deserializer=reservation__pb2.LogoutRequest.FromString,
                    response_serializer=reservation__pb2.LogoutResponse.SerializeToString,
            ),
            'FetchAvailableSlots': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchAvailableSlots,
                    request_deserializer=reservation__pb2.FetchAvailableSlotsRequest.FromString,
                    response_serializer=reservation__pb2.FetchAvailableSlotsResponse.SerializeToString,
            ),
            'MakeReservation': grpc.unary_unary_rpc_method_handler(
                    servicer.MakeReservation,
                    request_deserializer=reservation__pb2.MakeReservationRequest.FromString,
                    response_serializer=reservation__pb2.MakeReservationResponse.SerializeToString,
            ),
            'ViewReservations': grpc.unary_unary_rpc_method_handler(
                    servicer.ViewReservations,
                    request_deserializer=reservation__pb2.ViewReservationsRequest.FromString,
                    response_serializer=reservation__pb2.ViewReservationsResponse.SerializeToString,
            ),
            'CancelReservation': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelReservation,
                    request_deserializer=reservation__pb2.CancelReservationRequest.FromString,
                    response_serializer=reservation__pb2.CancelReservationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'reservation.ReservationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ReservationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PingServer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/reservation.ReservationService/PingServer',
            reservation__pb2.PingServerRequest.SerializeToString,
            reservation__pb2.PingServerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/reservation.ReservationService/CreateAccount',
            reservation__pb2.CreateAccountRequest.SerializeToString,
            reservation__pb2.CreateAccountResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/reservation.ReservationService/Login',
            reservation__pb2.LoginRequest.SerializeToString,
            reservation__pb2.LoginResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Logout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/reservation.ReservationService/Logout',
            reservation__pb2.LogoutRequest.SerializeToString,
            reservation__pb2.LogoutResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FetchAvailableSlots(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/reservation.ReservationService/FetchAvailableSlots',
            reservation__pb2.FetchAvailableSlotsRequest.SerializeToString,
            reservation__pb2.FetchAvailableSlotsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def MakeReservation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/reservation.ReservationService/MakeReservation',
            reservation__pb2.MakeReservationRequest.SerializeToString,
            reservation__pb2.MakeReservationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ViewReservations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/reservation.ReservationService/ViewReservations',
            reservation__pb2.ViewReservationsRequest.SerializeToString,
            reservation__pb2.ViewReservationsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CancelReservation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/reservation.ReservationService/CancelReservation',
            reservation__pb2.CancelReservationRequest.SerializeToString,
            reservation__pb2.CancelReservationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
